joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: &loop_hz 125

position_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints: &robot_joints
    - joint_a1
    - joint_a2
    - joint_a3
    - joint_a4
    - joint_a5
    - joint_a6
  gains: # Required because we're controlling an effort interface
    joint_a1: { p: 4000, d: 200, i: 1, i_clamp: 1 }
    joint_a2: { p: 10000, d: 200, i: 1, i_clamp: 1 }
    joint_a3: { p: 2000, d: 20, i: 1, i_clamp: 1 }
    joint_a4: { p: 500, d: 1, i: 1, i_clamp: 1 }
    joint_a5: { p: 500, d: 1, i: 1, i_clamp: 1 }
    joint_a6: { p: 10, d: 0.1, i: 0, i_clamp: 1 }
  constraints:
    goal_time: 50.0
    stopped_velocity_tolerance: 0.0
    joint_a1: { trajectory: 0.5, goal: 0.1 }
    joint_a2: { trajectory: 0.5, goal: 0.1 }
    joint_a3: { trajectory: 0.5, goal: 0.1 }
    joint_a4: { trajectory: 0.5, goal: 0.1 }
    joint_a5: { trajectory: 0.5, goal: 0.1 }
    joint_a6: { trajectory: 0.5, goal: 0.1 }
  stop_trajectory_duration: 0.5
  state_publish_rate: *loop_hz
  action_monitor_rate: 10

joint_group_eff_controller:
  type: position_controllers/JointGroupEffortController
  joints: *robot_joints

/ggazebo_ros_control:
  pid_gains:
    joint_a1:
      p: 4000
      i: 1
      d: 200
      i_clamp: 1
    joint_a2:
      p: 10000
      i: 1
      d: 200
      i_clamp: 1
    joint_a3:
      p: 2000
      i: 1
      d: 20
      i_clamp: 1
    joint_a4:
      p: 500
      i: 1
      d: 1
      i_clamp: 1
    joint_a5:
      p: 500
      i: 1
      d: 1
    joint_a6:
      p: 10
      i: 0
      d: 0.1
      i_clamp: 1
