tf_relations:
  - transform_1:
      translation:
        x: -0.061705
        y: 0.119431
        z: 0
      rotation:
        x: 0
        y: 0
        z: -0.00611458
        w: 0.999981
  - transform_2:
      translation:
        x: -0.0619096
        y: 0.1249
        z: 0
      rotation:
        x: 0
        y: 0
        z: -0.00649709
        w: 0.999979
  - transform_3:
      translation:
        x: -0.0554771
        y: 0.128828
        z: 0
      rotation:
        x: 0
        y: 0
        z: -0.00683657
        w: 0.999977
  - transform_4:
      translation:
        x: -0.0568012
        y: 0.126886
        z: 0
      rotation:
        x: 0
        y: 0
        z: -0.00673066
        w: 0.999977
  - transform_5:
      translation:
        x: -0.067771
        y: 0.122612
        z: 0
      rotation:
        x: 0
        y: 0
        z: -0.00672149
        w: 0.999977
  - transform_6:
      translation:
        x: -0.0659886
        y: 0.124039
        z: 0
      rotation:
        x: 0
        y: 0
        z: -0.00688796
        w: 0.999976
  - transform_7:
      translation:
        x: -0.0662312
        y: 0.124998
        z: 0
      rotation:
        x: 0
        y: 0
        z: -0.00660705
        w: 0.999978
  - transform_8:
      translation:
        x: -0.0613096
        y: 0.119337
        z: 0
      rotation:
        x: 0
        y: 0
        z: -0.0066234
        w: 0.999978
  - transform_9:
      translation:
        x: -0.0737564
        y: 0.116308
        z: 0
      rotation:
        x: 0
        y: 0
        z: -0.00611882
        w: 0.999981
  - transform_10:
      translation:
        x: -0.0804063
        y: 0.113974
        z: 0
      rotation:
        x: 0
        y: 0
        z: -0.00581687
        w: 0.999983
  - transform_11:
      translation:
        x: -0.0785936
        y: 0.116693
        z: 0
      rotation:
        x: 0
        y: 0
        z: -0.00580356
        w: 0.999983
  - transform_12:
      translation:
        x: -0.0838416
        y: 0.111043
        z: 0
      rotation:
        x: 0
        y: 0
        z: -0.00567609
        w: 0.999984
  - transform_13:
      translation:
        x: -0.0786066
        y: 0.116038
        z: 0
      rotation:
        x: 0
        y: 0
        z: -0.0058475
        w: 0.999983
  - transform_14:
      translation:
        x: -0.0834721
        y: 0.120647
        z: 0
      rotation:
        x: 0
        y: 0
        z: -0.00593393
        w: 0.999982
  - transform_15:
      translation:
        x: -0.0760395
        y: 0.117362
        z: 0
      rotation:
        x: 0
        y: 0
        z: -0.00601446
        w: 0.999982
  - transform_16:
      translation:
        x: -0.0784441
        y: 0.121333
        z: 0
      rotation:
        x: 0
        y: 0
        z: -0.0061036
        w: 0.999981
  - transform_17:
      translation:
        x: -0.0724696
        y: 0.115464
        z: 0
      rotation:
        x: 0
        y: 0
        z: -0.00596506
        w: 0.999982
  - transform_18:
      translation:
        x: -0.0734652
        y: 0.115407
        z: 0
      rotation:
        x: 0
        y: 0
        z: -0.00600338
        w: 0.999982
  - transform_19:
      translation:
        x: -0.0770835
        y: 0.11902
        z: 0
      rotation:
        x: 0
        y: 0
        z: -0.00619975
        w: 0.999981
  - transform_20:
      translation:
        x: -0.0778435
        y: 0.119856
        z: 0
      rotation:
        x: 0
        y: 0
        z: -0.00615537
        w: 0.999981
  - transform_21:
      translation:
        x: -0.0803766
        y: 0.119064
        z: 0
      rotation:
        x: 0
        y: 0
        z: -0.00596151
        w: 0.999982
  - transform_22:
      translation:
        x: -0.0837935
        y: 0.118898
        z: 0
      rotation:
        x: 0
        y: 0
        z: -0.00591251
        w: 0.999983
  - transform_23:
      translation:
        x: -0.0819114
        y: 0.118868
        z: 0
      rotation:
        x: 0
        y: 0
        z: -0.00587132
        w: 0.999983
  - transform_24:
      translation:
        x: -0.0737086
        y: 0.1221
        z: 0
      rotation:
        x: 0
        y: 0
        z: -0.0061047
        w: 0.999981
  - transform_25:
      translation:
        x: -0.0724358
        y: 0.12198
        z: 0
      rotation:
        x: 0
        y: 0
        z: -0.00606484
        w: 0.999982
  - transform_26:
      translation:
        x: -0.0695795
        y: 0.120307
        z: 0
      rotation:
        x: 0
        y: 0
        z: -0.00604747
        w: 0.999982
  - transform_27:
      translation:
        x: -0.0711972
        y: 0.119032
        z: 0
      rotation:
        x: 0
        y: 0
        z: -0.00596672
        w: 0.999982
  - transform_28:
      translation:
        x: -0.0695989
        y: 0.118726
        z: 0
      rotation:
        x: 0
        y: 0
        z: -0.00623745
        w: 0.999981
  - transform_29:
      translation:
        x: -0.0645977
        y: 0.115661
        z: 0
      rotation:
        x: 0
        y: 0
        z: -0.00637478
        w: 0.99998
  - transform_30:
      translation:
        x: -0.0608167
        y: 0.119767
        z: 0
      rotation:
        x: 0
        y: 0
        z: -0.006534
        w: 0.999979
  - transform_31:
      translation:
        x: -0.0690712
        y: 0.122344
        z: 0
      rotation:
        x: 0
        y: 0
        z: -0.00644721
        w: 0.999979
  - transform_32:
      translation:
        x: -0.0695894
        y: 0.124163
        z: 0
      rotation:
        x: 0
        y: 0
        z: -0.00624509
        w: 0.99998
  - transform_33:
      translation:
        x: -0.0646602
        y: 0.124034
        z: 0
      rotation:
        x: 0
        y: 0
        z: -0.00622751
        w: 0.999981
  - transform_34:
      translation:
        x: -0.0641117
        y: 0.12722
        z: 0
      rotation:
        x: 0
        y: 0
        z: -0.00654468
        w: 0.999979
  - transform_35:
      translation:
        x: -0.0653814
        y: 0.127686
        z: 0
      rotation:
        x: 0
        y: 0
        z: -0.00639804
        w: 0.99998
  - transform_36:
      translation:
        x: -0.0603874
        y: 0.127577
        z: 0
      rotation:
        x: 0
        y: 0
        z: -0.00652593
        w: 0.999979
  - transform_37:
      translation:
        x: -0.0580069
        y: 0.130142
        z: 0
      rotation:
        x: 0
        y: 0
        z: -0.00680952
        w: 0.999977
  - transform_38:
      translation:
        x: -0.0562264
        y: 0.128386
        z: 0
      rotation:
        x: 0
        y: 0
        z: -0.00715774
        w: 0.999974
  - transform_39:
      translation:
        x: -0.058483
        y: 0.127677
        z: 0
      rotation:
        x: 0
        y: 0
        z: -0.00708589
        w: 0.999975
  - transform_40:
      translation:
        x: -0.060074
        y: 0.125267
        z: 0
      rotation:
        x: 0
        y: 0
        z: -0.006849
        w: 0.999977
  - transform_41:
      translation:
        x: -0.0623683
        y: 0.125893
        z: 0
      rotation:
        x: 0
        y: 0
        z: -0.00669437
        w: 0.999978
  - transform_42:
      translation:
        x: -0.062652
        y: 0.127653
        z: 0
      rotation:
        x: 0
        y: 0
        z: -0.00679839
        w: 0.999977
  - transform_43:
      translation:
        x: -0.0643372
        y: 0.128704
        z: 0
      rotation:
        x: 0
        y: 0
        z: -0.00681332
        w: 0.999977
  - transform_44:
      translation:
        x: -0.0608666
        y: 0.127972
        z: 0
      rotation:
        x: 0
        y: 0
        z: -0.00685367
        w: 0.999977
  - transform_45:
      translation:
        x: -0.0580549
        y: 0.128813
        z: 0
      rotation:
        x: 0
        y: 0
        z: -0.00679865
        w: 0.999977
  - transform_46:
      translation:
        x: -0.0577125
        y: 0.128259
        z: 0
      rotation:
        x: 0
        y: 0
        z: -0.00701205
        w: 0.999975
  - transform_47:
      translation:
        x: -0.0600562
        y: 0.129067
        z: 0
      rotation:
        x: 0
        y: 0
        z: -0.0068902
        w: 0.999976
  - transform_48:
      translation:
        x: -0.0602329
        y: 0.126325
        z: 0
      rotation:
        x: 0
        y: 0
        z: -0.00681675
        w: 0.999977
  - transform_49:
      translation:
        x: -0.059254
        y: 0.125242
        z: 0
      rotation:
        x: 0
        y: 0
        z: -0.00687052
        w: 0.999976
  - transform_50:
      translation:
        x: -0.0616041
        y: 0.125527
        z: 0
      rotation:
        x: 0
        y: 0
        z: -0.00661627
        w: 0.999978
  - transform_51:
      translation:
        x: -0.0632371
        y: 0.127709
        z: 0
      rotation:
        x: 0
        y: 0
        z: -0.00660826
        w: 0.999978
  - transform_52:
      translation:
        x: -0.0607978
        y: 0.127995
        z: 0
      rotation:
        x: 0
        y: 0
        z: -0.00651841
        w: 0.999979
  - transform_53:
      translation:
        x: -0.0542685
        y: 0.129551
        z: 0
      rotation:
        x: 0
        y: 0
        z: -0.00665517
        w: 0.999978
  - transform_54:
      translation:
        x: -0.0593965
        y: 0.130465
        z: 0
      rotation:
        x: 0
        y: 0
        z: -0.00663046
        w: 0.999978
  - transform_55:
      translation:
        x: -0.0582858
        y: 0.127609
        z: 0
      rotation:
        x: 0
        y: 0
        z: -0.00657179
        w: 0.999978
  - transform_56:
      translation:
        x: -0.0590326
        y: 0.127699
        z: 0
      rotation:
        x: 0
        y: 0
        z: -0.00667699
        w: 0.999978
  - transform_57:
      translation:
        x: -0.0565991
        y: 0.129674
        z: 0
      rotation:
        x: 0
        y: 0
        z: -0.0069527
        w: 0.999976
  - transform_58:
      translation:
        x: -0.0583714
        y: 0.127761
        z: 0
      rotation:
        x: 0
        y: 0
        z: -0.00695775
        w: 0.999976
  - transform_59:
      translation:
        x: -0.0623297
        y: 0.129928
        z: 0
      rotation:
        x: 0
        y: 0
        z: -0.00691496
        w: 0.999976
  - transform_60:
      translation:
        x: -0.0604544
        y: 0.13217
        z: 0
      rotation:
        x: 0
        y: 0
        z: -0.00707364
        w: 0.999975
  - transform_61:
      translation:
        x: -0.0676043
        y: 0.123993
        z: 0
      rotation:
        x: 0
        y: 0
        z: -0.00665461
        w: 0.999978
  - transform_62:
      translation:
        x: -0.061526
        y: 0.121979
        z: 0
      rotation:
        x: 0
        y: 0
        z: -0.00679336
        w: 0.999977
  - transform_63:
      translation:
        x: -0.0670956
        y: 0.119595
        z: 0
      rotation:
        x: 0
        y: 0
        z: -0.00679212
        w: 0.999977
  - transform_64:
      translation:
        x: -0.0680259
        y: 0.125313
        z: 0
      rotation:
        x: 0
        y: 0
        z: -0.00665241
        w: 0.999978
  - transform_65:
      translation:
        x: -0.061264
        y: 0.12649
        z: 0
      rotation:
        x: 0
        y: 0
        z: -0.0067093
        w: 0.999977
  - transform_66:
      translation:
        x: -0.0567381
        y: 0.122366
        z: 0
      rotation:
        x: 0
        y: 0
        z: -0.00674301
        w: 0.999977
  - transform_67:
      translation:
        x: -0.057605
        y: 0.128638
        z: 0
      rotation:
        x: 0
        y: 0
        z: -0.00680974
        w: 0.999977
  - transform_68:
      translation:
        x: -0.0618399
        y: 0.132026
        z: 0
      rotation:
        x: 0
        y: 0
        z: -0.00668863
        w: 0.999978
  - transform_69:
      translation:
        x: -0.0701155
        y: 0.12768
        z: 0
      rotation:
        x: 0
        y: 0
        z: -0.00579625
        w: 0.999983
  - transform_70:
      translation:
        x: -0.068262
        y: 0.122555
        z: 0
      rotation:
        x: 0
        y: 0
        z: -0.00603238
        w: 0.999982
  - transform_71:
      translation:
        x: -0.0637658
        y: 0.12466
        z: 0
      rotation:
        x: 0
        y: 0
        z: -0.00633164
        w: 0.99998
  - transform_72:
      translation:
        x: -0.0660151
        y: 0.12552
        z: 0
      rotation:
        x: 0
        y: 0
        z: -0.00617586
        w: 0.999981
  - transform_73:
      translation:
        x: -0.0686528
        y: 0.126254
        z: 0
      rotation:
        x: 0
        y: 0
        z: -0.00570492
        w: 0.999984
  - transform_74:
      translation:
        x: -0.0721482
        y: 0.125966
        z: 0
      rotation:
        x: 0
        y: 0
        z: -0.00566667
        w: 0.999984
  - transform_75:
      translation:
        x: -0.0812062
        y: 0.123139
        z: 0
      rotation:
        x: 0
        y: 0
        z: -0.00543932
        w: 0.999985
  - transform_76:
      translation:
        x: -0.0811386
        y: 0.122783
        z: 0
      rotation:
        x: 0
        y: 0
        z: -0.00553811
        w: 0.999985
  - transform_77:
      translation:
        x: -0.0758783
        y: 0.122601
        z: 0
      rotation:
        x: 0
        y: 0
        z: -0.00563865
        w: 0.999984
  - transform_78:
      translation:
        x: -0.0818774
        y: 0.12005
        z: 0
      rotation:
        x: 0
        y: 0
        z: -0.00573873
        w: 0.999984
  - transform_79:
      translation:
        x: -0.0820297
        y: 0.120896
        z: 0
      rotation:
        x: 0
        y: 0
        z: -0.00568667
        w: 0.999984
  - transform_80:
      translation:
        x: -0.0737401
        y: 0.119919
        z: 0
      rotation:
        x: 0
        y: 0
        z: -0.00557225
        w: 0.999984
  - transform_81:
      translation:
        x: -0.0818216
        y: 0.118058
        z: 0
      rotation:
        x: 0
        y: 0
        z: -0.00517942
        w: 0.999987
  - transform_82:
      translation:
        x: -0.0829795
        y: 0.120903
        z: 0
      rotation:
        x: 0
        y: 0
        z: -0.00501771
        w: 0.999987
  - transform_83:
      translation:
        x: -0.0950101
        y: 0.111215
        z: 0
      rotation:
        x: 0
        y: 0
        z: -0.00397898
        w: 0.999992
  - transform_84:
      translation:
        x: -0.094976
        y: 0.108908
        z: 0
      rotation:
        x: 0
        y: 0
        z: -0.00388042
        w: 0.999992
  - transform_85:
      translation:
        x: -0.104219
        y: 0.104858
        z: 0
      rotation:
        x: 0
        y: 0
        z: -0.00347843
        w: 0.999994
