controller_list:
  - name: position_trajectory_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - joint_a1
      - joint_a2
      - joint_a3
      - joint_a4
      - joint_a5
      - joint_a6
    constraints:
    constraints:
      goal_time: 60.0 # Override default
      stopped_velocity_tolerance: 0.0
      joint_a1: { trajectory: 1.0, goal: 0.1 }
      joint_a2: { trajectory: 1.0, goal: 0.1 }
      joint_a3: { trajectory: 1.0, goal: 0.1 }
      joint_a4: { trajectory: 1.0, goal: 0.1 }
      joint_a5: { trajectory: 1.0, goal: 0.1 }
      joint_a6: { trajectory: 1.0, goal: 0.1 }
    state_publish_rate: 50 # Defaults to 50
    action_monitor_rate: 20 # Defaults to 20
    stop_trajectory_duration: 0.5